name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Heroku Git
        run: | 
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/lark-designer-client-staging.git
          git push heroku master
